/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program.laundry;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Laundry;

/**
 *
 * @author user1
 */
public class FormLaundryMichael extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLaundryMichael.class.getName());

    /**
     * Creates new form FormLaundryMichael
     */
    public FormLaundryMichael() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJenisLayanan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNamaPelanggan = new javax.swing.JTextField();
        jTextFieldBeratCucian = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonCuciKering = new javax.swing.JRadioButton();
        jRadioButtonCuciSetrika = new javax.swing.JRadioButton();
        jButtonInput = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePenatu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nama Pelanggan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Berat Cucian");

        jTextFieldNamaPelanggan.addActionListener(this::jTextFieldNamaPelangganActionPerformed);

        jTextFieldBeratCucian.addActionListener(this::jTextFieldBeratCucianActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Jenis Layanan");

        jLabel5.setText("KG");

        buttonGroupJenisLayanan.add(jRadioButtonCuciKering);
        jRadioButtonCuciKering.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonCuciKering.setText("Cuci Kering");

        buttonGroupJenisLayanan.add(jRadioButtonCuciSetrika);
        jRadioButtonCuciSetrika.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButtonCuciSetrika.setText("Cuci Setrika");
        jRadioButtonCuciSetrika.addActionListener(this::jRadioButtonCuciSetrikaActionPerformed);

        jButtonInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInput.setText("I N P U T");
        jButtonInput.addActionListener(this::jButtonInputActionPerformed);

        jTablePenatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pelanggan", "Berat Cucian", "Jenis Layanan", "Biaya"
            }
        ));
        jScrollPane1.setViewportView(jTablePenatu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInput)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBeratCucian, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jRadioButtonCuciKering)
                            .addComponent(jRadioButtonCuciSetrika))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBeratCucian, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonCuciKering))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCuciSetrika)
                .addGap(18, 18, 18)
                .addComponent(jButtonInput)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCuciSetrikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCuciSetrikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCuciSetrikaActionPerformed

    private void jTextFieldNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaPelangganActionPerformed

    private void jTextFieldBeratCucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBeratCucianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeratCucianActionPerformed

    private void jButtonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputActionPerformed
        String namaPelanggan = jTextFieldNamaPelanggan.getText().trim();
        
//        int beratCucian = Integer.parseInt(jTextFieldBeratCucian.getText());
        int beratCucian;
        try{
            beratCucian = Integer.parseInt(jTextFieldBeratCucian.getText().trim());
        } catch (Exception e){
            beratCucian = 0;
            System.out.println("Terjadi Exception" + e);
            System.out.println("Berat Cucian Diubah Menjadi 0");
        }
        String jenisLayanan = "";
        if(jRadioButtonCuciKering.isSelected()) jenisLayanan = "Cuci Kering";
        else if(jRadioButtonCuciSetrika.isSelected()) jenisLayanan = "Cuci Setrika";
        
        Laundry laundry = new Laundry(namaPelanggan, beratCucian, jenisLayanan);
        
        String pesan = "======\nNama Pelanggan: " + laundry.getNamaPelanggan()
                        + "\nBerat Cucian: " + laundry.getBeratCucian() + "kg" 
                        + "\nJenis Layanan: " + laundry.getJenisLayanan()
                        + "\nBiaya Rp." + laundry.getBiaya(); 
        
        JOptionPane.showMessageDialog(null, pesan, "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        
        Object[] barisData = {
            laundry.getNamaPelanggan(),
            laundry.getBeratCucian(),
            laundry.getJenisLayanan(),
            laundry.getBiaya()
        };
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTablePenatu.getModel();
        defaultTableModel.addRow(barisData);
    }//GEN-LAST:event_jButtonInputActionPerformed
    public boolean validasiInput(){
        if(jTextFieldNamaPelanggan.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Nama Pelanggan tidak boleh kosong");
            return false;
        } else if (jTextFieldBeratCucian.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Berat Cucian harap diisi");
            return false;
        } else {
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLaundryMichael().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJenisLayanan;
    private javax.swing.JButton jButtonInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonCuciKering;
    private javax.swing.JRadioButton jRadioButtonCuciSetrika;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePenatu;
    private javax.swing.JTextField jTextFieldBeratCucian;
    private javax.swing.JTextField jTextFieldNamaPelanggan;
    // End of variables declaration//GEN-END:variables
}
