/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuis2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Hero;

/**
 *
 * @author user1
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton6 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNamaHero = new javax.swing.JTextField();
        jTextFieldSkill1Hero = new javax.swing.JTextField();
        jRadioButtonAssasin = new javax.swing.JRadioButton();
        jRadioButtonTank = new javax.swing.JRadioButton();
        jRadioButtonMage = new javax.swing.JRadioButton();
        jRadioButtonFighter = new javax.swing.JRadioButton();
        jRadioButtonSupport = new javax.swing.JRadioButton();
        jRadioButtonMarksman = new javax.swing.JRadioButton();
        jTextFieldSkill2Hero = new javax.swing.JTextField();
        jTextFieldSkill3Hero = new javax.swing.JTextField();
        jTextFieldSkill4Hero = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOutput = new javax.swing.JTable();

        jRadioButton6.setText("jRadioButton6");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Hero");

        jLabel2.setText("Tipe Hero");

        jLabel3.setText("Skill 1 Hero");

        jLabel4.setText("Skill 2 Hero");

        jLabel5.setText("Skill 3 Hero");

        jLabel6.setText("Skill 4 Hero");

        jTextFieldNamaHero.addActionListener(this::jTextFieldNamaHeroActionPerformed);

        jTextFieldSkill1Hero.addActionListener(this::jTextFieldSkill1HeroActionPerformed);

        jRadioButtonAssasin.setText("Assasin");
        jRadioButtonAssasin.addActionListener(this::jRadioButtonAssasinActionPerformed);

        jRadioButtonTank.setText("Tank");
        jRadioButtonTank.addActionListener(this::jRadioButtonTankActionPerformed);

        jRadioButtonMage.setText("Mage");
        jRadioButtonMage.addActionListener(this::jRadioButtonMageActionPerformed);

        jRadioButtonFighter.setText("Fighter");
        jRadioButtonFighter.addActionListener(this::jRadioButtonFighterActionPerformed);

        jRadioButtonSupport.setText("Support");
        jRadioButtonSupport.addActionListener(this::jRadioButtonSupportActionPerformed);

        jRadioButtonMarksman.setText("Marksman");
        jRadioButtonMarksman.addActionListener(this::jRadioButtonMarksmanActionPerformed);

        jTextFieldSkill2Hero.addActionListener(this::jTextFieldSkill2HeroActionPerformed);

        jTextFieldSkill3Hero.addActionListener(this::jTextFieldSkill3HeroActionPerformed);

        jTextFieldSkill4Hero.addActionListener(this::jTextFieldSkill4HeroActionPerformed);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(this::jButtonSubmitActionPerformed);

        jTableOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Hero", "Tipe Hero", "Skill 1 Hero", "Skill 2 Hero", "Skill 3 Hero", "Skill 4 Hero"
            }
        ));
        jScrollPane2.setViewportView(jTableOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNamaHero, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonSubmit)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonAssasin)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButtonTank)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButtonMage)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButtonFighter)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButtonSupport)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonMarksman))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldSkill4Hero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(jTextFieldSkill3Hero, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldSkill1Hero, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldSkill2Hero, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNamaHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonAssasin)
                    .addComponent(jRadioButtonTank)
                    .addComponent(jRadioButtonMage)
                    .addComponent(jRadioButtonFighter)
                    .addComponent(jRadioButtonSupport)
                    .addComponent(jRadioButtonMarksman))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSkill1Hero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSkill2Hero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSkill3Hero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSkill4Hero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmit)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaHeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaHeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaHeroActionPerformed

    private void jRadioButtonAssasinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAssasinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAssasinActionPerformed

    private void jRadioButtonTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTankActionPerformed

    private void jRadioButtonMageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMageActionPerformed

    private void jRadioButtonFighterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFighterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFighterActionPerformed

    private void jRadioButtonSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSupportActionPerformed

    private void jRadioButtonMarksmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMarksmanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMarksmanActionPerformed

    private void jTextFieldSkill1HeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSkill1HeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSkill1HeroActionPerformed

    private void jTextFieldSkill2HeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSkill2HeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSkill2HeroActionPerformed

    private void jTextFieldSkill3HeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSkill3HeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSkill3HeroActionPerformed

    private void jTextFieldSkill4HeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSkill4HeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSkill4HeroActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String namaHero = jTextFieldNamaHero.getText();
        
    String tipeHero = "";

    if (jRadioButtonAssasin.isSelected()) {
        tipeHero = "Assasin";
    } else if (jRadioButtonTank.isSelected()) {
        tipeHero = "Tank";
    } else if (jRadioButtonMage.isSelected()) {
        tipeHero = "Mage";
    } else if (jRadioButtonFighter.isSelected()) {
        tipeHero = "Fighter";
    } else if (jRadioButtonSupport.isSelected()) {
        tipeHero = "Support";
    } else if (jRadioButtonMarksman.isSelected()) {
        tipeHero = "Marksman";
    }

    String skill1 = jTextFieldSkill1Hero.getText();
    String skill2 = jTextFieldSkill2Hero.getText();
    String skill3 = jTextFieldSkill3Hero.getText();
    String skill4 = jTextFieldSkill4Hero.getText();

    Hero hero = new Hero(namaHero, tipeHero, skill1, skill2, skill3, skill4);
            
    Object[] barisData = {
        hero.getNamaHero(),
        hero.getTipeHero(),
        hero.getSkill1Hero(),
        hero.getSkill2Hero(),
        hero.getSkill3Hero(),
        hero.getSkill4Hero()
    };
    
        DefaultTableModel model = (DefaultTableModel) jTableOutput.getModel();
        model.addRow(barisData);
//    String pesan = "========================"
//                 + "\nNama Hero : " + namaHero
//                 + "\nTipe Hero : " + tipeHero
//                 + "\nSkill 1   : " + skill1
//                 + "\nSkill 2   : " + skill2
//                 + "\nSkill 3   : " + skill3
//                 + "\nSkill 4   : " + skill4
//                 + "\n========================";
//
//    JOptionPane.showMessageDialog(
//            null,
//            pesan,
//            ":: INFORMASI HERO ::",
//            JOptionPane.INFORMATION_MESSAGE
//    );
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButtonAssasin;
    private javax.swing.JRadioButton jRadioButtonFighter;
    private javax.swing.JRadioButton jRadioButtonMage;
    private javax.swing.JRadioButton jRadioButtonMarksman;
    private javax.swing.JRadioButton jRadioButtonSupport;
    private javax.swing.JRadioButton jRadioButtonTank;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableOutput;
    private javax.swing.JTextField jTextFieldNamaHero;
    private javax.swing.JTextField jTextFieldSkill1Hero;
    private javax.swing.JTextField jTextFieldSkill2Hero;
    private javax.swing.JTextField jTextFieldSkill3Hero;
    private javax.swing.JTextField jTextFieldSkill4Hero;
    // End of variables declaration//GEN-END:variables
}
